[pytest]
addopts = -v

markers =
    math: mark test as related to mathematical operations
    accumulator: mark test as related to the Accumulator class
    api: mark test as related to API endpoints
    duckduckgo: mark test as related to DuckDuckGo search functionality
    ui: mark test as related to user interface
    acme_bank: mark test as related to Playwright browser automation
testpaths = tests